// Auto-generated by gasnuki
// Do NOT edit this file manually.
export type ServerScripts = {
  /**
   * Webアプリとして公開された際にGETリクエストを処理する関数
   * この関数は、ViteでビルドされたフロントエンドのHTMLを返します
   */
  doGet(): GoogleAppsScript.HTML.HtmlOutput;

  /**
   * ユーザー名を受け取り、挨拶メッセージを返すGAS関数
   * @param name ユーザーの名前
   * @returns 挨拶メッセージ
   */
  sayHello(name: string): string;

  /**
   * 現在時刻を文字列として返すGAS関数
   */
  getCurrentTime(): string;
};

// Auto-generated Types for GoogleAppsScript in client-side code

type RemoveReturnType<T> = {
  [P in keyof T]: T[P] extends (...args: infer A) => any
    ? (...args: A) => void
    : T[P];
};

type _AppsScriptRun = RemoveReturnType<ServerScripts> & {
  // [key: string]: (...args: any[]) => any;
  withSuccessHandler: <T = string | number | boolean | undefined, U = any>(
    callback: (returnValues: T, userObject?: U) => void,
  ) => _AppsScriptRun;
  withFailureHandler: <U = any>(
    callback: (error: Error, userObject?: U) => void,
  ) => _AppsScriptRun;
  withUserObject: <U = any>(userObject: U) => _AppsScriptRun;
};

type _AppsScriptHistoryFunction = (
  stateObject: object,
  params: object,
  hash: string,
) => void;

interface _WebAppLovacationType {
  hash: string;
  parameter: Record<string, string>;
  parameters: Record<string, string[]>;
}

export declare interface GoogleClientSideApi {
  script: {
    run: _AppsScriptRun;
    url: {
      getLocation: (
        callback: (location: _WebAppLovacationType) => void,
      ) => void;
    };
    history: {
      push: _AppsScriptHistoryFunction;
      replace: _AppsScriptHistoryFunction;
      setChangeHandler: (
        callback: (e: {
          state: object;
          location: _WebAppLovacationType;
        }) => void,
      ) => void;
    };
  };
}

declare global {
  const google: GoogleClientSideApi;
}
