// Auto-generated by gasnuki
// Do NOT edit this file manually.
import type { ApprovalRequest, ApprovalStatus } from './approval';

type RequestParameters<T extends string = string> = {
  queryString: string | null;
  parameter: Partial<Record<T, string> & Record<string, string>>;
  parameters: Partial<Record<T, string[]> & Record<string, string[]>>;
  pathInfo: string;
  contextPath: '';
  contentLength: number;
  postData: {
    length: number;
    type: string;
    contents: string;
    name: 'postData';
  };
};

type UrlParameterKeys = 'page' | 'id';

export type EmbeddedParameters = RequestParameters<UrlParameterKeys> & {
  userAddress: string;
};

export type ServerScripts = {
  /**
   * 稟議申請データをスプレッドシートに保存するGAS関数
   * @param requestData 申請データ
   * @returns 保存された申請データ（IDが付与されたもの）
   */
  createApprovalRequest(requestData: {
    title: string;
    description: string;
    amount: number;
    benefits: string;
    avoidableRisks: string;
    applicant: string;
  }): string;

  /**
   * スプレッドシートからすべての稟議申請データを取得するGAS関数
   * @returns 稟議申請データの配列
   */
  getApprovalRequests(): string;

  /**
   * 稟議申請のステータスを更新するGAS関数
   * @param id 稟議ID
   * @param status 更新後のステータス ('approved' or 'rejected')
   * @param reason 却下理由 (却下の場合のみ)
   * @returns 更新された稟議データ
   */
  updateApprovalStatus(id: string, status: ApprovalStatus, reason?: string): string;
}

// Auto-generated Types for GoogleAppsScript in client-side code

export type RemoveReturnType<T> = {
  [P in keyof T]: T[P] extends (...args: infer A) => any
    ? (...args: A) => void
    : T[P];
};

type _AppsScriptRun = RemoveReturnType<ServerScripts> & {
  [key: string]: (...args: any[]) => any;
  withSuccessHandler: <T = string | number | boolean | undefined, U = any>(
    callback: (returnValues: T, userObject?: U) => void,
  ) => _AppsScriptRun;
  withFailureHandler: <U = any>(
    callback: (error: Error, userObject?: U) => void,
  ) => _AppsScriptRun;
  withUserObject: <U = any>(userObject: U) => _AppsScriptRun;
};

type _AppsScriptHistoryFunction = (
  stateObject: object,
  params: object,
  hash: string,
) => void;

interface _WebAppLovacationType {
  hash: string;
  parameter: Record<string, string>;
  parameters: Record<string, string[]>;
}

export declare interface GoogleClientSideApi {
  script: {
    run: _AppsScriptRun;
    url: {
      getLocation: (
        callback: (location: _WebAppLovacationType) => void,
      ) => void;
    };
    history: {
      push: _AppsScriptHistoryFunction;
      replace: _AppsScriptHistoryFunction;
      setChangeHandler: (
        callback: (e: {
          state: object;
          location: _WebAppLovacationType;
        }) => void,
      ) => void;
    };
  };
}

declare global {
  const google: GoogleClientSideApi;
}
