// Auto-generated by gasnuki
// Do NOT edit this file manually.
export type ServerScripts = {
  doGet(): GoogleAppsScript.HTML.HtmlOutput;

  /**
   * 稟議申請データをスプレッドシートに保存するGAS関数
   * @param requestData 申請データ
   * @returns 保存された申請データ（IDが付与されたもの）
   */
  createApprovalRequest(requestData: {
    title: string;
    description: string;
    amount: number;
    benefits: string;
    avoidableRisks: string;
    applicant: string;
  }): string;
}

// Auto-generated Types for GoogleAppsScript in client-side code

export type RemoveReturnType<T> = {
  [P in keyof T]: T[P] extends (...args: infer A) => any
    ? (...args: A) => void
    : T[P];
};

type _AppsScriptRun = RemoveReturnType<ServerScripts> & {
  [key: string]: (...args: any[]) => any;
  withSuccessHandler: <T = string | number | boolean | undefined, U = any>(
    callback: (returnValues: T, userObject?: U) => void,
  ) => _AppsScriptRun;
  withFailureHandler: <U = any>(
    callback: (error: Error, userObject?: U) => void,
  ) => _AppsScriptRun;
  withUserObject: <U = any>(userObject: U) => _AppsScriptRun;
};

type _AppsScriptHistoryFunction = (
  stateObject: object,
  params: object,
  hash: string,
) => void;

interface _WebAppLovacationType {
  hash: string;
  parameter: Record<string, string>;
  parameters: Record<string, string[]>;
}

export declare interface GoogleClientSideApi {
  script: {
    run: _AppsScriptRun;
    url: {
      getLocation: (
        callback: (location: _WebAppLovacationType) => void,
      ) => void;
    };
    history: {
      push: _AppsScriptHistoryFunction;
      replace: _AppsScriptHistoryFunction;
      setChangeHandler: (
        callback: (e: {
          state: object;
          location: _WebAppLovacationType;
        }) => void,
      ) => void;
    };
  };
}

declare global {
  const google: GoogleClientSideApi;
}
