// Auto-generated by gasnuki
// Do NOT edit this file manually.

import type { ApprovalRequest } from '../approval';

export type ServerScripts = {
  /**
   * 新しい稟議申請を作成し、スプレッドシートに追記する
   * @param formData 稟議申請フォームのデータ
   * @returns 成功メッセージ
   */
  createApprovalRequest(formData: {
    title: string;
    amount: number;
    benefits: string;
    avoidableRisks: string;
    approver: string;
  }): string;

  /**
   * スプレッドシートからすべての稟議申請を取得する
   * @returns 稟議申請の配列
   */
  getApprovalRequests(): ApprovalRequest[];

  /**
   * 稟議申請のステータスを更新する
   * 承認者として指定されたユーザーのみが実行可能
   * @param id 稟議申請ID
   * @param newStatus 新しいステータス ('approved' or 'rejected')
   * @param reason 却下理由 (却下時のみ)
   * @returns 成功メッセージ
   */
  updateApprovalStatus(
    id: string,
    newStatus: 'approved' | 'rejected',
    reason?: string,
  ): string;

  /**
   * スクリプトロックを取得し、コールバックを排他制御下で実行するユーティリティ関数。
   *
   * @param callback 排他制御下で実行したい関数
   * @returns なし
   */
  useLock(callback: () => void): void;
};

// Auto-generated Types for GoogleAppsScript in client-side code

export type RemoveReturnType<T> = {
  [P in keyof T]: T[P] extends (...args: infer A) => any
    ? (...args: A) => void
    : T[P];
};

type _AppsScriptRun = RemoveReturnType<ServerScripts> & {
  [key: string]: (...args: any[]) => any;
  withSuccessHandler: <T = string | number | boolean | undefined, U = any>(
    callback: (returnValues: T, userObject?: U) => void,
  ) => _AppsScriptRun;
  withFailureHandler: <U = any>(
    callback: (error: Error, userObject?: U) => void,
  ) => _AppsScriptRun;
  withUserObject: <U = any>(userObject: U) => _AppsScriptRun;
};

type _AppsScriptHistoryFunction = (
  stateObject: object,
  params: object,
  hash: string,
) => void;

interface _WebAppLovacationType {
  hash: string;
  parameter: Record<string, string>;
  parameters: Record<string, string[]>;
}

export declare interface GoogleClientSideApi {
  script: {
    run: _AppsScriptRun;
    url: {
      getLocation: (
        callback: (location: _WebAppLovacationType) => void,
      ) => void;
    };
    history: {
      push: _AppsScriptHistoryFunction;
      replace: _AppsScriptHistoryFunction;
      setChangeHandler: (
        callback: (e: {
          state: object;
          location: _WebAppLovacationType;
        }) => void,
      ) => void;
    };
  };
}

declare global {
  const google: GoogleClientSideApi;
}
