name: Push to Gist

on:
  push:
    branches:
      - main

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load files excluding .gistignore patterns
        id: files
        run: |
          find . -type f | sed 's|^\./||' > all_files.txt
          grep -v '^#' .gistignore | grep -v '^$' > exclude_patterns.txt
          grep -f exclude_patterns.txt all_files.txt > excluded.txt
          comm -23 <(sort all_files.txt) <(sort excluded.txt) > filtered_files.txt
          echo "FILES=$(paste -sd ' ' filtered_files.txt)" >> $GITHUB_ENV

      - name: Find files to push
        run: |
          GIST_ID="b44be26669d7fe80628bb684be4cfae5"
          for FILE in $FILES; do
            echo "Updating $FILE"
            curl -s \
              -X PATCH \
              -H "Authorization: token ${{ secrets.GIST_TOKEN }}" \
              -H "Content-Type: application/json" \
              "https://api.github.com/gists/$GIST_ID" \
              -d "$(jq -n --arg name "$FILE" --arg content "$(cat "$FILE")" \
                '{files: {($name): {content: $content}}}')"
          done
